directories:
  output: release
  buildResources: build
appId: com.xujmzd.cineflow
productName: CineFlow
files:
  - filter:
      - electron/**/*
      - dist/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: electron/assets/icon.ico
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: CineFlow
  installerIcon: electron/assets/icon.ico
  uninstallerIcon: electron/assets/icon.ico
  installerHeaderIcon: electron/assets/icon.ico
  uninstallDisplayName: CineFlow 0.1.0
  license: LICENSE.txt
electronVersion: 28.3.3
